In [1]:
from torchvision import datasets
from torchvision.transforms import ToTensor
import torch
import matplotlib
import matplotlib.pyplot as plt


In [2]:
    kernel1 = torch.tensor([[0, 0, 0],
                            [1, 1, 1],
                            [0, 0, 0]], dtype=torch.float32)

    kernel2 = torch.tensor([[0, 1, 0],
                            [0, 1, 0],
                            [0, 1, 0]], dtype=torch.float32)

    kernel3 = torch.tensor([[0, 0, 1],
                            [0, 1, 0],
                            [1, 0, 0]], dtype=torch.float32)

    kernel4 = torch.tensor([[1, 0, 0],
                            [0, 1, 0],
                            [0, 0, 1]], dtype=torch.float32)

    kernel5 = torch.tensor([[0, 1, 0],
                            [1, 1, 1],
                            [0, 1, 0]], dtype=torch.float32)
    kernels = [kernel1, kernel2, kernel3, kernel4, kernel5]


In [ ]:

from models.SetA1.A1DT.CNN import A1DT
from models.SetA1.A1HF.CNN import A1HF
from models.SetA1.A1HT.CNN import A1HT
from models.SetA2.A2DT.CNN import A2DT
from models.SetA2.A2HF.CNN import A2HF
from models.SetA2.A2HT.CNN import A2HT

A1HF = A1HF(kernels)
A1HT = A1HT(kernels)
A1DT = A1DT()

A2DT = A2DT()
A2HT = A2HT(kernels)
A2HF = A2HF(kernels)

In [65]:

wA1HF = A1HF.conv1.weight
wA1DT = A1DT.conv1.weight
wA1HT = A1HT.conv1.weight

wA2HF = A2HF.conv1.weight
wA2DT = A2DT.conv1.weight
wA2HT = A2HT.conv1.weight

fcA1HF = A1HF.fc1.weight
fcA1DT = A1DT.fc1.weight
fcA1HT = A1HT.fc1.weight
fcA2HF = A2HF.fc1.weight
fcA2DT = A2DT.fc1.weight
fcA2HT = A2HT.fc1.weight

w2A2HF = A2HF.conv2.weight
w2A2HT = A2HT.conv2.weight
w2A2DT = A2DT.conv2.weight




In [66]:
print("conv1 weight matrix of A1HF:", wA1HF)


conv1 weight matrix of A1HF: Parameter containing:
tensor([[[[0., 0., 0.],
          [1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 1., 0.],
          [0., 1., 0.],
          [0., 1., 0.]]],


        [[[0., 0., 1.],
          [0., 1., 0.],
          [1., 0., 0.]]],


        [[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]],


        [[[0., 1., 0.],
          [1., 1., 1.],
          [0., 1., 0.]]]])


In [67]:
print("conv1 weight matrix of A2HF:", wA2HF)


conv1 weight matrix of A2HF: Parameter containing:
tensor([[[[0., 0., 0.],
          [1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 1., 0.],
          [0., 1., 0.],
          [0., 1., 0.]]],


        [[[0., 0., 1.],
          [0., 1., 0.],
          [1., 0., 0.]]],


        [[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]],


        [[[0., 1., 0.],
          [1., 1., 1.],
          [0., 1., 0.]]]])


In [68]:
print("conv1 weight matrix of A1HT:", wA1HT)


conv1 weight matrix of A1HT: Parameter containing:
tensor([[[[0., 0., 0.],
          [1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 1., 0.],
          [0., 1., 0.],
          [0., 1., 0.]]],


        [[[0., 0., 1.],
          [0., 1., 0.],
          [1., 0., 0.]]],


        [[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]],


        [[[0., 1., 0.],
          [1., 1., 1.],
          [0., 1., 0.]]]], requires_grad=True)


In [69]:
print("conv1 weight matrix of A2HT:", wA2HT)


conv1 weight matrix of A2HT: Parameter containing:
tensor([[[[0., 0., 0.],
          [1., 1., 1.],
          [0., 0., 0.]]],


        [[[0., 1., 0.],
          [0., 1., 0.],
          [0., 1., 0.]]],


        [[[0., 0., 1.],
          [0., 1., 0.],
          [1., 0., 0.]]],


        [[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]],


        [[[0., 1., 0.],
          [1., 1., 1.],
          [0., 1., 0.]]]], requires_grad=True)


In [70]:
print("conv1 weight matrix of A1DT:", wA1DT)


conv1 weight matrix of A1DT: Parameter containing:
tensor([[[[-0.0025,  0.1788, -0.2743],
          [-0.2453, -0.1284,  0.0894],
          [-0.0066,  0.2643, -0.0296]]],


        [[[ 0.0882, -0.1007, -0.0655],
          [-0.3184, -0.2208, -0.1374],
          [ 0.0123,  0.1318,  0.2000]]],


        [[[-0.2260, -0.1452,  0.1211],
          [ 0.2768, -0.0686,  0.2494],
          [-0.0537,  0.0353,  0.3018]]],


        [[[-0.3092, -0.2098, -0.0844],
          [-0.1299,  0.2880, -0.2161],
          [-0.1534, -0.2329, -0.3122]]],


        [[[-0.1946,  0.2865,  0.1487],
          [ 0.1616,  0.0175, -0.1709],
          [ 0.0564, -0.3112, -0.2409]]]], requires_grad=True)


In [71]:
print("conv1 weight matrix of A2DT:", wA2DT)


conv1 weight matrix of A2DT: Parameter containing:
tensor([[[[-0.0025,  0.1788, -0.2743],
          [-0.2453, -0.1284,  0.0894],
          [-0.0066,  0.2643, -0.0296]]],


        [[[ 0.0882, -0.1007, -0.0655],
          [-0.3184, -0.2208, -0.1374],
          [ 0.0123,  0.1318,  0.2000]]],


        [[[-0.2260, -0.1452,  0.1211],
          [ 0.2768, -0.0686,  0.2494],
          [-0.0537,  0.0353,  0.3018]]],


        [[[-0.3092, -0.2098, -0.0844],
          [-0.1299,  0.2880, -0.2161],
          [-0.1534, -0.2329, -0.3122]]],


        [[[-0.1946,  0.2865,  0.1487],
          [ 0.1616,  0.0175, -0.1709],
          [ 0.0564, -0.3112, -0.2409]]]], requires_grad=True)


In [74]:
print("conv2 weight matrix of A2HF:", w2A2HF)


conv2 weight matrix of A2HF: Parameter containing:
tensor([[[[ 0.0953,  0.1482,  0.0592],
          [ 0.0201,  0.1000, -0.0878],
          [ 0.0278, -0.1156, -0.1033]],

         [[-0.0770,  0.0675,  0.0600],
          [-0.0883,  0.0450,  0.0818],
          [-0.0188,  0.0057,  0.0345]],

         [[ 0.0925,  0.1431, -0.1149],
          [-0.0546,  0.0586,  0.1235],
          [ 0.1297,  0.1315,  0.0297]],

         [[-0.1296,  0.0137, -0.0933],
          [-0.1389,  0.1324,  0.1133],
          [-0.1487,  0.0279, -0.0251]],

         [[-0.0245, -0.0682,  0.0573],
          [-0.0883,  0.0546,  0.0754],
          [ 0.1067,  0.0557, -0.1475]]],


        [[[-0.0967,  0.0744,  0.0312],
          [-0.1163, -0.0858,  0.1402],
          [ 0.1004, -0.0650, -0.0375]],

         [[-0.1420, -0.0027, -0.1123],
          [-0.1150, -0.0082,  0.0224],
          [-0.0610,  0.0885, -0.0907]],

         [[ 0.1353,  0.1022, -0.1257],
          [-0.0371,  0.0067,  0.0217],
          [ 0.0354,  0.0585,  0.0089

In [75]:
print("conv2 weight matrix of A2HT:", w2A2HT)


conv2 weight matrix of A2HT: Parameter containing:
tensor([[[[ 0.0953,  0.1482,  0.0592],
          [ 0.0201,  0.1000, -0.0878],
          [ 0.0278, -0.1156, -0.1033]],

         [[-0.0770,  0.0675,  0.0600],
          [-0.0883,  0.0450,  0.0818],
          [-0.0188,  0.0057,  0.0345]],

         [[ 0.0925,  0.1431, -0.1149],
          [-0.0546,  0.0586,  0.1235],
          [ 0.1297,  0.1315,  0.0297]],

         [[-0.1296,  0.0137, -0.0933],
          [-0.1389,  0.1324,  0.1133],
          [-0.1487,  0.0279, -0.0251]],

         [[-0.0245, -0.0682,  0.0573],
          [-0.0883,  0.0546,  0.0754],
          [ 0.1067,  0.0557, -0.1475]]],


        [[[-0.0967,  0.0744,  0.0312],
          [-0.1163, -0.0858,  0.1402],
          [ 0.1004, -0.0650, -0.0375]],

         [[-0.1420, -0.0027, -0.1123],
          [-0.1150, -0.0082,  0.0224],
          [-0.0610,  0.0885, -0.0907]],

         [[ 0.1353,  0.1022, -0.1257],
          [-0.0371,  0.0067,  0.0217],
          [ 0.0354,  0.0585,  0.0089

In [76]:
print("conv2 weight matrix of A2DT:", w2A2DT)


conv2 weight matrix of A2DT: Parameter containing:
tensor([[[[ 0.0953,  0.1482,  0.0592],
          [ 0.0201,  0.1000, -0.0878],
          [ 0.0278, -0.1156, -0.1033]],

         [[-0.0770,  0.0675,  0.0600],
          [-0.0883,  0.0450,  0.0818],
          [-0.0188,  0.0057,  0.0345]],

         [[ 0.0925,  0.1431, -0.1149],
          [-0.0546,  0.0586,  0.1235],
          [ 0.1297,  0.1315,  0.0297]],

         [[-0.1296,  0.0137, -0.0933],
          [-0.1389,  0.1324,  0.1133],
          [-0.1487,  0.0279, -0.0251]],

         [[-0.0245, -0.0682,  0.0573],
          [-0.0883,  0.0546,  0.0754],
          [ 0.1067,  0.0557, -0.1475]]],


        [[[-0.0967,  0.0744,  0.0312],
          [-0.1163, -0.0858,  0.1402],
          [ 0.1004, -0.0650, -0.0375]],

         [[-0.1420, -0.0027, -0.1123],
          [-0.1150, -0.0082,  0.0224],
          [-0.0610,  0.0885, -0.0907]],

         [[ 0.1353,  0.1022, -0.1257],
          [-0.0371,  0.0067,  0.0217],
          [ 0.0354,  0.0585,  0.0089

In [78]:
print("fc1 weight matrix of A1HF:", fcA1HF)


fc1 weight matrix of A1HF: Parameter containing:
tensor([[ 0.0204,  0.0318,  0.0127,  ...,  0.0130, -0.0108,  0.0220],
        [ 0.0253,  0.0046, -0.0025,  ...,  0.0140, -0.0155,  0.0299],
        [-0.0219,  0.0147, -0.0229,  ..., -0.0202,  0.0140,  0.0290],
        ...,
        [ 0.0310, -0.0064, -0.0178,  ..., -0.0254, -0.0078,  0.0096],
        [ 0.0032, -0.0085,  0.0042,  ..., -0.0090, -0.0021,  0.0181],
        [ 0.0166, -0.0208, -0.0277,  ...,  0.0163, -0.0147, -0.0317]],
       requires_grad=True)


In [79]:
print("fc1 weight matrix of A1HT:", fcA1HT)


fc1 weight matrix of A1HT: Parameter containing:
tensor([[ 0.0204,  0.0318,  0.0127,  ...,  0.0130, -0.0108,  0.0220],
        [ 0.0253,  0.0046, -0.0025,  ...,  0.0140, -0.0155,  0.0299],
        [-0.0219,  0.0147, -0.0229,  ..., -0.0202,  0.0140,  0.0290],
        ...,
        [ 0.0310, -0.0064, -0.0178,  ..., -0.0254, -0.0078,  0.0096],
        [ 0.0032, -0.0085,  0.0042,  ..., -0.0090, -0.0021,  0.0181],
        [ 0.0166, -0.0208, -0.0277,  ...,  0.0163, -0.0147, -0.0317]],
       requires_grad=True)


In [80]:
print("fc1 weight matrix of A1DT:", fcA1DT)


fc1 weight matrix of A1DT: Parameter containing:
tensor([[ 0.0204,  0.0318,  0.0127,  ...,  0.0130, -0.0108,  0.0220],
        [ 0.0253,  0.0046, -0.0025,  ...,  0.0140, -0.0155,  0.0299],
        [-0.0219,  0.0147, -0.0229,  ..., -0.0202,  0.0140,  0.0290],
        ...,
        [ 0.0310, -0.0064, -0.0178,  ..., -0.0254, -0.0078,  0.0096],
        [ 0.0032, -0.0085,  0.0042,  ..., -0.0090, -0.0021,  0.0181],
        [ 0.0166, -0.0208, -0.0277,  ...,  0.0163, -0.0147, -0.0317]],
       requires_grad=True)


In [81]:
print("fc1 weight matrix of A2HF:", fcA2HF)


fc1 weight matrix of A2HF: Parameter containing:
tensor([[-0.0152,  0.0326, -0.0146,  ..., -0.0231, -0.0073,  0.0115],
        [ 0.0070, -0.0100, -0.0527,  ...,  0.0267,  0.0297, -0.0319],
        [ 0.0430,  0.0518, -0.0208,  ...,  0.0211,  0.0344, -0.0092],
        ...,
        [ 0.0264,  0.0009,  0.0290,  ..., -0.0011,  0.0289,  0.0431],
        [-0.0282, -0.0117, -0.0475,  ..., -0.0337,  0.0277, -0.0338],
        [ 0.0362,  0.0211, -0.0129,  ...,  0.0279, -0.0524, -0.0293]],
       requires_grad=True)


In [82]:
print("fc1 weight matrix of A2HT:", fcA2HT)


fc1 weight matrix of A2HT: Parameter containing:
tensor([[-0.0152,  0.0326, -0.0146,  ..., -0.0231, -0.0073,  0.0115],
        [ 0.0070, -0.0100, -0.0527,  ...,  0.0267,  0.0297, -0.0319],
        [ 0.0430,  0.0518, -0.0208,  ...,  0.0211,  0.0344, -0.0092],
        ...,
        [ 0.0264,  0.0009,  0.0290,  ..., -0.0011,  0.0289,  0.0431],
        [-0.0282, -0.0117, -0.0475,  ..., -0.0337,  0.0277, -0.0338],
        [ 0.0362,  0.0211, -0.0129,  ...,  0.0279, -0.0524, -0.0293]],
       requires_grad=True)


In [83]:
print("fc1 weight matrix of A2DT:", fcA2DT)


fc1 weight matrix of A2DT: Parameter containing:
tensor([[-0.0152,  0.0326, -0.0146,  ..., -0.0231, -0.0073,  0.0115],
        [ 0.0070, -0.0100, -0.0527,  ...,  0.0267,  0.0297, -0.0319],
        [ 0.0430,  0.0518, -0.0208,  ...,  0.0211,  0.0344, -0.0092],
        ...,
        [ 0.0264,  0.0009,  0.0290,  ..., -0.0011,  0.0289,  0.0431],
        [-0.0282, -0.0117, -0.0475,  ..., -0.0337,  0.0277, -0.0338],
        [ 0.0362,  0.0211, -0.0129,  ...,  0.0279, -0.0524, -0.0293]],
       requires_grad=True)


# NORMA DELLA DISTANZA TRA I PESI DEI CONV1 LAYERS

In [54]:
print("Distance norm between weights of conv1 layer:")
print("|A1DT-A2DT|:",float(torch.norm(wA1DT-wA2DT)))
print("|A1HF-A2HF|:",float(torch.norm(wA1HF-wA2HF)))
print("|A1HT-A2HT|:",float(torch.norm(wA1HT-wA2HT)))

Distance norm between weights of conv1 layer:
|A1DT-A2DT|: 0.0
|A1HF-A2HF|: 0.0
|A1HT-A2HT|: 0.0


# NORMA DELLA DISTANZA TRA I PESI DEI CONV2 LAYERS

In [53]:

print("Distance norm between weights of conv2 layer:")
print("|A2HF-A2HT|:",float(torch.norm(w2A2HF-w2A2HT)))
print("|A2HF-A2DT|:",float(torch.norm(w2A2HF-w2A2DT)))
print("|A2HT-A2DT|:",float(torch.norm(w2A2HT-w2A2DT)))

Distance norm between weights of conv2 layer:
|A2HF-A2HT|: 0.0
|A2HF-A2DT|: 0.0
|A2HT-A2DT|: 0.0


# NORMA DELLA DIFFERENZA TRA I PESI DELLE FULLY CONNECTED

In [46]:
print("Distance norm between fully connected layers of the 2 sets A1 and A2:")

print("Set A1:")
print("|A1HF - A1DT|:",float(torch.norm(fcA1HF-fcA1DT)))
print("|A1HF - A1HT|:",float(torch.norm(fcA1HF-fcA1HT)))
print("|A1DT - A1HT|:",float(torch.norm(fcA1DT-fcA1HT)))
print("Set A2:")
print("|A2HF - A2DT|:",float(torch.norm(fcA2HF-fcA2DT)))
print("|A2HF - A2HT|:",float(torch.norm(fcA2HF-fcA2HT)))
print("|A2DT - A2HT|:",float(torch.norm(fcA2DT-fcA2HT)))


Distance norm between fully connected layers of the 2 sets A1 and A2:
Set A1:
|A1HF - A1DT|: 0.0
|A1HF - A1HT|: 0.0
|A1DT - A1HT|: 0.0
Set A2:
|A2HF - A2DT|: 0.0
|A2HF - A2HT|: 0.0
|A2DT - A2HT|: 0.0
